// =====================================================================
// ECO IMPACT CALCULATIONS
//
// Single source of truth for converting solar generation (kWh) into
// two user-facing metrics: CO2 saved and equivalent trees planted.
// Both GenerationEcoCard (and any other screen/nav tab) should import
// from here instead of re-implementing the formula, so the numbers
// shown on Home / Power / Fault always stay in sync.
// =====================================================================

// ── CONSTANTS ────────────────────────────────────────────────────────

// Average CO2 emitted per kWh of grid electricity in India (kg/kWh).
// Every kWh generated by the solar plant is 1 kWh the grid didn't have
// to produce, so this is the amount of CO2 "saved" per kWh generated.
// (Central Electricity Authority / standard solar-industry approximation.)
export const CO2_KG_PER_KWH = 0.82;

// Average amount of CO2 a single mature tree absorbs in one year (kg).
// Used to convert a CO2 mass into an equivalent number of trees.
export const KG_CO2_PER_TREE = 21;


// ── CORE FORMULAS ────────────────────────────────────────────────────

/**
 * CO2 saved (kg) = total energy generated (kWh) × emission factor (kg/kWh)
 *
 * @param {number|string} totalGenerationKWh - lifetime/total generation in kWh
 * @returns {number} CO2 saved in kilograms, or NaN if input is invalid
 */
export function calculateCO2SavedKg(totalGenerationKWh) {
    const kwh = Number(totalGenerationKWh);

    if (!Number.isFinite(kwh) || kwh < 0) {
        return NaN;
    }

    return kwh * CO2_KG_PER_KWH;
}

/**
 * Trees planted (equivalent) = CO2 saved (kg) ÷ CO2 absorbed per tree per year (kg)
 *
 * Accepts either the CO2 already saved (kg) or the raw generation (kWh) —
 * pass { fromGeneration: true } to compute CO2 internally first.
 *
 * @param {number|string} value
 * @param {{ fromGeneration?: boolean }} [options]
 * @returns {number} equivalent number of trees, or NaN if input is invalid
 */
export function calculateTreesPlanted(value, options = {}) {
    const co2Kg = options.fromGeneration
        ? calculateCO2SavedKg(value)
        : Number(value);

    if (!Number.isFinite(co2Kg) || co2Kg < 0) {
        return NaN;
    }

    return co2Kg / KG_CO2_PER_TREE;
}

/**
 * Convenience helper: goes straight from total generation (kWh) to both
 * metrics at once, so callers only need one function call.
 *
 * @param {number|string} totalGenerationKWh
 * @returns {{ co2SavedKg: number, treesPlanted: number }}
 */
export function calculateEcoImpact(totalGenerationKWh) {
    const co2SavedKg = calculateCO2SavedKg(totalGenerationKWh);

    const treesPlanted = Number.isFinite(co2SavedKg)
        ? co2SavedKg / KG_CO2_PER_TREE
        : NaN;

    return { co2SavedKg, treesPlanted };
}


// ── DISPLAY FORMATTERS ───────────────────────────────────────────────

/**
 * Formats a kg value as tonnes with 2 decimal places, e.g. 1234 -> "1.23"
 */
export function formatCO2Tonnes(co2Kg) {
    if (!Number.isFinite(co2Kg)) {
        return "--";
    }

    return (co2Kg / 1000).toFixed(2);
}

/**
 * Formats a raw tree count as a rounded, comma-grouped whole number,
 * e.g. 1234.7 -> "1,235"
 */
export function formatTreeCount(trees) {
    if (!Number.isFinite(trees)) {
        return "--";
    }

    return Math.round(trees).toLocaleString("en-IN");
}
